- chuffed/flatzinc/parser.tab.cpp
- chuffed/flatzinc/parser.yxx
`fzn-chuffed` with option `-a` breaks if we provide flatzinc input from stdin, i.e., if we invoke the solving pipeline as follows
cat model.mzn | mzn2fzn --globals-dir chuffed --input-from-stdin --no-output-ozn --output-to-stdout | fzn-chuffed -a
[...]
/media/psf/Home/Programming/MiniZinc/libminizinc-deploy/ide/linux/build-chuffed-64/chuffed/chuffed/core/engine.cpp:419: Not yet supported
the following assertion from https://github.com/chuffed/chuffed/blob/master/chuffed/core/engine.cpp#L419 aborts the execution:
if (outputs.size() == 0) NOT_SUPPORTED;
With flatzinc file input (`fzn-chuffed -a <file>.fzn`) or invoking above solving pipeline without option `-a`, `fzn-chuffed` works as expected.
I could track down the problem to function `FlatZinc::solve(std::istream& is, std::ostream& err)` …
> define output variables when parser reads from stdin

- chuffed/flatzinc/mznlib/redefinitions.mzn
- chuffed/flatzinc/registry.cpp
- chuffed/primitives/binary.cpp
- chuffed/primitives/primitives.h
Chuffed already has support for integer half-refied constraints; however, you cannot access these from FlatZinc. This PR adds the following predicates to the registry:
```
predicate int_eq_imp(var int: a, var int: b, var bool: r);
predicate int_ne_imp(var int: a, var int: b, var bool: r);
predicate int_ge_imp(var int: a, var int: b, var bool: r);
predicate int_gt_imp(var int: a, var int: b, var bool: r);
predicate int_le_imp(var int: a, var int: b, var bool: r);
predicate int_lt_imp(var int: a, var int: b, var bool: r);
```
The naming of these predicates is consistent with the naming of the half-refied predicates in Gecode.
Like fully reified constraints partially known half-reified constraints can make holes within the domain of a variable. It therefore follows the same steps as reified …
> FlatZinc: Add support for integer half-reification constraints

- chuffed/core/engine.cpp
- chuffed/core/engine.h
- chuffed/core/options.cpp
- chuffed/core/options.h
- chuffed/flatzinc/ast.h
- chuffed/flatzinc/flatzinc.cpp
- chuffed/flatzinc/lexer.lxx
- chuffed/flatzinc/mznlib/chuffed.mzn
- chuffed/flatzinc/mznlib/redefinitions.mzn
Currently Chuffed has it's own function to determine the number of conflicts that is very similar to Luby. This PR adds various other common cutoffs:
- Constant
- Linear
- Luby
- Geometric
These new strategies are accessible from command line and as FlatZinc annotation conform to the annotation and flags used by Gecode.
*Note that this changes the `--restart-base` flag to `--restart-scale`*.
The following annotations are added to the Chuffed MiniZinc library:
```
% restart after fixed number of nodes
annotation restart_constant(int: nodes);
% restart with scaled Luby sequence
annotation restart_luby(int: scale);
% restart with scaled geometric sequence (scale*base^n in the n-th iteration)
annotation restart_geometric(float: base, int: scale);
% restart with linear sequence (scale*n in the …
```
> Restart Strategies

- CMakeLists.txt
This PR just contains a small change to the CMake configurations. With the change we use the official CMake packages for Flex and Bison to generate the FlatZinc parser.
> Use Bison and Flex CMake packages

- chuffed/flatzinc/registry.cpp
These changes fix the remaining uses of the `hasAtom` method used on null pointers, extending #26. This method was still used in the register. This will fix #27.
> Fix segmentation fault in register

- chuffed/core/stats.cpp
This is a very small PR that fixes the objective statistic output. The objective should only be in the output when solving a optimisation problem.
> Fix objective statistic output

- chuffed/vars/int-var-ll.cpp
When the bounds where updated on lazy literals we didn't account for the
values that where already eliminated through "hole punching"
This PR fixes  #32
> Fix the updating of the bounds for lazy literals

- chuffed/core/stats.cpp
- chuffed/flatzinc/flatzinc.cpp
Sparse Literal variables should be used in cases where the number of
values in the domain is sparse. This commit enables two cases:
- When the domain is bigger than the eager limit, but contains less
values than the eager limit.
- When the heuristic from specializeSL is reached
> Add the usage of IntVarSL in fzn-chuffed

- chuffed/flatzinc/parser.yxx
This PR introduces a small fix for the FlatZinc parser which solves #37. The fix adds an extra check to the usages of the "hasCall" method to make sure the object on which it is called actually exist.
> Fix GCC6+ segmentation fault in the FlatZinc parser

- chuffed/flatzinc/parser.tab.cpp
- chuffed/flatzinc/parser.tab.h
This PR updates the cached version of the parser that is included when Bison and Flex are not available. The current included version can cause segfaults on some FlatZinc files.
We might want to consider making Bison/Flex a requirement for compilation as these are common tools and this problem tends to happen quite often.
> Update cached parser

- chuffed/support/misc.h
This is a simple change that hide the absolute path when compiling in release mode. This means that, for example, when `fzn-chuffed` is shipped in MiniZinc, the error will be:
```
arithmetic.cpp:605: Cannot handle non-sign-fixed vars
```
instead of
```
/Users/jdek0001/Playground/runner/builds/373b1426/0/minizinc/vendor/chuffed/chuffed/primitives/arithmetic.cpp:605: Cannot handle non-sign-fixed vars
```
> Hide full error path when building in release

- CMakeLists.txt
- chuffed/flatzinc/parser.tab.cpp
- chuffed/flatzinc/parser.tab.h
This PR fixes the include order of the Chuffed build process. The current process would prefer to generate a new Bison parser, but it would include the cached header. The new behaviour is to used the generated header.
In addition I've updated the cached Bison Parser
> Fix order of include directories

- chuffed/flatzinc/mznlib/fzn_count_neq.mzn
- chuffed/flatzinc/mznlib/fzn_count_neq_par.mzn
- chuffed/flatzinc/registry.cpp
The new MiniZinc library added the usage of a `bool_sum_ne`, but there is no internal implementation. The `bool_linear` function used for Boolean linear comparisons for all the other summations does not have a case for `IRT_NE` resulting in an error when `bool_sum_ne` is used in the FlatZinc.
This PR just removes the usage of `bool_sum_ne` relying on the redefinition (as was the case before the changes)
> Remove the unimplemented bool_sum_ne from mznlib and registry

- chuffed/flatzinc/flatzinc.cpp
Ensures that even if the var count is initially zero, it can still be grown as required.
This prevents a crash for flatzinc like
```
solve minimize 1;
```
> Grow FlatZinc variable vector even if size is 0

- CMakeLists.txt
- chuffed/core/engine.cpp
- chuffed/core/options.cpp
Fixes compilation of chuffed when the profiler submodule is not present, and also fixes cleanup of the profiler where for some reason `std::cout` gets broken if you disconnect when not actually connected on Unix.
> Fix cpprofiler integration

- CMakeLists.txt
Because of the Flex dependency on the Bison target, we should only trigger the Flex target if a compatible version of Bison is found.
> Do not trigger flex unless Bison is available

- CMakeLists.txt
Just a small typo that causes an extra level in the relative path to the binary file.
> Fix the path of solver files in the generation of binary relative path

- .gitmodules
- chuffed.msc.in
- chuffed/core/options.cpp
Renames the `-cpprofiler` flag to `--cp-profiler` to be consistent with normal flag naming. This enables support for search profiling in the upcoming release of the MiniZinc IDE.
The CP-Profiler integration will now be maintained at https://gitlab.com/minizinc/cp-profiler-integration.
TODO: We should look into the possibility of using CMake to fetch the profiler integration submodule rather than requiring users to do it when building.
> Rename -cpprofiler flag to --cp-profiler, update submodule URL

- chuffed/primitives/arithmetic.cpp
The explanations ignore that `v_min` and `v_max` were used in the propagation rules, leading to incorrect explanations.
> bug fix: incomplete explanations in TimesAll propagator

- chuffed/core/engine.cpp
- chuffed/primitives/arithmetic.cpp
Fixed issue in search engine and TimesAll propagaor where the `--no-learn` (`so.lazy`) flag was ignored and Chuffed tried to access non-existing literals, causing a crash.
> Fixed issue with --no-learn flag
